language: java

# TODO: is there a way to define the matrix avoiding duplication?
matrix:
  include:
  - os: linux
    sudo: required
    group: edge
    services:
      - docker
    env:
      - SCALA_VERSION=2.11.12
      - XGBOOST_VERSION=${XGBOOST_BASE_VERSION}_2.11
  - os: osx
    osx_image: xcode8
    env:
      - SCALA_VERSION=2.11.12
      - XGBOOST_VERSION=${XGBOOST_BASE_VERSION}_2.11

env:
  global:
    - HADOOP_VERSION=2.6.0-cdh5.5.0
    - SPARK_VERSION=2.4.1
    - XGBOOST_BASE_VERSION=0.91.0-criteo-20190723-7ba5648

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/install.sh; fi


script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/test_and_package.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        docker run
            -e XGBOOST_VERSION
            -e HADOOP_VERSION
            -e SCALA_VERSION
            -e SPARK_VERSION
            -e TRAVIS_OS_NAME
            -v `pwd`:/xgboost-jars:rw
            centos:centos6
            /bin/bash -c "bash -xe /xgboost-jars/travis/docker.sh";
    fi

deploy:
  provider: releases
  api_key:
    secure: j6jqSH+xk8bdMqLmO9F+ziTyFROW2UqF6WPyJsBdqE0PVkqFj4Hnc4ML4G1HVrtzvL2+5dkj6Y8i2r6eTumHYlVkjeVGJlPEwQCIH7Jj1uGnEgr/sSt2S19pbdP4mLaTF7U1EJNsHXwG6iD3h8Gu9czC4xeK0XYdc9bC7QcYjCPodeIVoqRY4rd98yLAjOyacg2aXyPuoxgXJQAuLyEyo44vtXx/aeCAeI4qsC5yTfSKYX3LBSPv38Pu1jMIIOf3fhvEFKy002yGnMPoFIBK9Q62oI7mVn8LeqvDfsqeYXskfHxA1LjKR+vP9yATn+9i2l4y0QOJj7+JpeSWbEjOuzNfZX9vuLXtEi9aAHEUMyy6ZvM9MVp55OBKUSWHhsimtWKiE2Ey1bl8Tjr6As0ntArzrL5XO2aYrdpJiCzgkw0OO5XcmOLG5h8dHZzfPVKH45yheutWFm73kr9z75V665W/yQ4YMAsw5OjXhDnLosFkd+GkOAzGh3Chbbv9sA0U1emCvnr+ajAPUkTAtAf/J7fw3DD0nuunR60rw7DZnVX0TB21v3OF+15/qvFhOQmNo68ES+8O4DIXn5NZdQy71JSdsbnM1LpMjmQ8gPu0O+hFRaUKqdS0a0MHT7NfrbZ8t25fGnAK81OLb/PTuhzsI81jwbWpV1kRo2Xi/ofEOQw=    
  file:
    - xgboost4j-$XGBOOST_VERSION-$TRAVIS_OS_NAME.jar
    - xgboost4j-spark-$XGBOOST_VERSION.jar
  skip_cleanup: true
  overwrite: true
  on:
    repo: criteo-forks/xgboost-jars
    tags: true
