language: java

# TODO: is there a way to define the matrix avoiding duplication?
matrix:
  include:
    - os: linux
      sudo: required
      group: edge
      services:
        - docker
      env:
        - SCALA_VERSION=2.11.12
        - SCALA_BINARY_VERSION=2.11
        - XGBOOST_COMPLETE_VERSION=${SCALA_BINARY_VERSION}-${XGBOOST_BASE_VERSION}

    - os: osx
      osx_image: xcode9.3
      env:
        - SCALA_VERSION=2.11.12
        - SCALA_BINARY_VERSION=2.11
        - XGBOOST_COMPLETE_VERSION=${SCALA_BINARY_VERSION}-${XGBOOST_BASE_VERSION}

env:
  global:
    - HADOOP_VERSION=2.6.0-cdh5.5.0
    - SPARK_VERSION=2.4.1
    - XGBOOST_VERSION_DMLC=1.1.0
    - XGBOOST_BASE_VERSION=${XGBOOST_VERSION_DMLC}-criteo-20200802-071ef500

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew update;
    brew upgrade cmake;
    fi;

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/install.sh; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sh travis/test_and_package.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    sh travis/install.sh;
    sh xgboost/jvm-packages/dev/build-linux.sh --skip-tests;
    cp xgboost/jvm-packages/xgboost4j/target/xgboost4j_$XGBOOST_COMPLETE_VERSION.jar $TRAVIS_BUILD_DIR/xgboost4j_$XGBOOST_COMPLETE_VERSION-$TRAVIS_OS_NAME.jar;
    cp xgboost/jvm-packages/xgboost4j-spark/target/xgboost4j-spark_$XGBOOST_COMPLETE_VERSION.jar $TRAVIS_BUILD_DIR/xgboost4j-spark_$XGBOOST_COMPLETE_VERSION.jar;
    fi;

deploy:
  provider: releases
  api_key:
    secure: "Ld9WpDeB5T+IYmfCdZCxB6gi6hlcEOpKBoYN+vMo/zTPkDAzqdau4IsRFY0zcxlVPV4p5A3hs1KhAVwhTB74jhUhkzMBtAcUNyTXqi+riFC6KnbJu1D8hEkfjI1ei5Nh4n3JnbhxSqLv12N8Nl7BxFA8BYfdtBpXf1AuHDDsnAOjAuSlOZlxoOZUql/f85PX8SbYB4ZEVWuSuwt6qLq0SY+iaZLvS9JMivp+FCgHwEiiB6tEl5fnhQew1csU5PkWU6Zj1My0OWdXD+YNs0B3wkavHknC8xn37fj+iPOZSaKPkGSslC4EmhNX9pamtfjHaffJyzWD3GKFQNXg4phRw+qoFo3oc98CyZMlFAXJg3GOa508cpCv+Zfua6yPhbNHGB1lUVGphW4Pz7QscX15NVnteYsjPeWYlHJjbmiueJpk0KUYtk5uzz2jNP7SEaPBFhEdxC7OUAqhieToxnhErnwZIR8ISkK9NLk6ak2pQX0ZM/L5oLCytq8qcxT7gXncKUba2SSgvAAC4rnY7M8M3ydJCDZTzArjf4ei6Axddc+dsa2ItS9aDmZ4ZOw6jkgamc0ypaaxKQKUqTN+7+L6rWUwi8z4lEDmzuj50CugWXneo0tij79M7VnA6m4tNnIq3y+btgcZQNioFDgXHNCMkJRwvKwDS69BS7GZEFeGdu0="
  file:
    - xgboost4j_$XGBOOST_COMPLETE_VERSION-$TRAVIS_OS_NAME.jar
    - xgboost4j-spark_$XGBOOST_COMPLETE_VERSION.jar
  skip_cleanup: true
  overwrite: true
  on:
    repo: criteo-forks/xgboost-jars
    tags: true
