platform: x64
image: Visual Studio 2015

environment:
  global:
    LIBHDFS_DIR: '%APPVEYOR_BUILD_FOLDER%\libhdfs-dev'
    HADOOP_VERSION: 2.6.0-cdh5.5.0
    SPARK_VERSION: 2.3.1
    JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    XGBOOST_BASE_VERSION: 0.81-criteo-20181206
  matrix:
    - SCALA_VERSION: 2.11.12
      XGBOOST_VERSION: '%XGBOOST_BASE_VERSION%_2.11'

clone_script:
  - git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
  - cd %APPVEYOR_BUILD_FOLDER%
  - git checkout -qf %APPVEYOR_REPO_COMMIT%
  - git submodule update --init --recursive

install:
  - 'SET PATH=%VS140COMNTOOLS%\..\IDE;C:\Python36-x64;%PATH%'
  - ps: If (!(Test-Path -Path $env:LIBHDFS_DIR)) { iex 'python.exe install_libhdfs.py' }

build_script:
  - 'C:\Python36-x64\python.exe install_xgboost.py'

test_script:
  - cd xgboost
  - 'SET HADOOP_HDFS_HOME=%CD%'
  - cd jvm-packages
  - mvn -q package -pl :xgboost4j
  # 'kryoSerializer test' in xgboost4j-spark seems to fail on Windows.
  # The issue has been reported upstream, see dmlc/xgboost#2394.
  - mvn -q package -pl :xgboost4j-spark -am -DskipTests -Dmaven.test.skip -Prelease
  - 'copy xgboost4j\target\xgboost4j-%XGBOOST_VERSION%.jar
         %APPVEYOR_BUILD_FOLDER%\xgboost4j-%XGBOOST_VERSION%-win64.jar'
  - 'copy xgboost4j\target\xgboost4j-%XGBOOST_VERSION%-sources.jar
         %APPVEYOR_BUILD_FOLDER%\xgboost4j-%XGBOOST_VERSION%-sources.jar'
  - 'copy xgboost4j-spark\target\xgboost4j-spark-%XGBOOST_VERSION%.jar
         %APPVEYOR_BUILD_FOLDER%\xgboost4j-spark-%XGBOOST_VERSION%.jar'
  - 'copy xgboost4j-spark\target\xgboost4j-spark-%XGBOOST_VERSION%-sources.jar
         %APPVEYOR_BUILD_FOLDER%\xgboost4j-spark-%XGBOOST_VERSION%-sources.jar'
  - 'copy pom.xml %APPVEYOR_BUILD_FOLDER%\xgboost-jvm-%XGBOOST_VERSION%.pom'

cache:
  - '%LIBHDFS_DIR%'

artifacts:
  - path: 'xgboost-jvm-%XGBOOST_VERSION%.pom'
  - path: 'xgboost4j-%XGBOOST_VERSION%-win64.jar'
  - path: 'xgboost4j-%XGBOOST_VERSION%-sources.jar'
  - path: 'xgboost4j-spark-%XGBOOST_VERSION%.jar'
  - path: 'xgboost4j-spark-%XGBOOST_VERSION%-sources.jar'

deploy:
  provider: GitHub
  tag: '$(XGBOOST_BASE_VERSION)'
  description: ''
  force_update: true
  auth_token:
    secure: 'GAsVDc+Y0V9vOCuF+W9l7RVr2r1IoOgRfuRm6Jgd3fjIgylg2C4wudvzI25D4XYD'
  on:
    appveyor_repo_tag: true
